import { type AppType } from "next/dist/shared/lib/utils";
import Head from "next/head";

import "~/styles/globals.css";

const MyApp: AppType = ({ Component, pageProps }) => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="font-plex-mono min-w-screen flex min-h-screen flex-col items-center justify-between">
        {/* <Navbar /> */}
        <main className="my-4 flex min-h-full w-full flex-col items-center justify-center gap-4 rounded-lg px-4 py-8">
          <Component {...pageProps} />
        </main>
        {/* <Footer /> */}
      </div>
    </>
  );
};

export default MyApp;
